INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (1, 'Broché', 1, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (2, 'Broché', 1, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (3, 'Poche', 1, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (4, 'Poche', 1, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (5, 'Roman', 1, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (6, 'Roman', 1, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (7, 'Poche', 2, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (8, 'Poche', 2, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (9, 'Roman', 2, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (10, 'Roman', 2, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (11, 'Broché', 3, 1, 'Indisponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (12, 'Broché', 3, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (13, 'Roman', 3, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (14, 'Roman', 3, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (15, 'Roman', 4, 1, 'Indisponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (16, 'Roman', 4, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (17, 'Poche', 5, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (18, 'Poche', 5, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (19, 'Roman', 5, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (20, 'Roman', 5, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (21, 'Broché', 6, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (22, 'Broché', 6, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (23, 'Poche', 7, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (24, 'Poche', 7, 2, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (25, 'Roman', 7, 1, 'Disponible');
INSERT INTO library.copy (id, format, book_id, library_id, status) VALUES (26, 'Roman', 7, 2, 'Disponible');

INSERT INTO library.emprunt (id, emprunt_date, return_date, is_extended, customer_id, copy_id) VALUES (1, '2020-09-22', '2020-12-15', 1, 3, 11);
INSERT INTO library.emprunt (id, emprunt_date, return_date, is_extended, customer_id, copy_id) VALUES (3, '2020-09-08', '2020-10-06', 0, 3, 15);