version: '2'
services:
  library.db:
    image: mysql
    ports:
      - "127.0.0.1:9032:3306"
    volumes:
      - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=brichet
      - MYSQL_ROOT_PASSWORD=admin

